architecture: replication

auth:
  enabled: false  # Simplified for internal use

master:
  count: 1
  
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
  
  service:
    type: ClusterIP
    port: 6379

replica:
  replicaCount: 2
  
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""

sentinel:
  enabled: true
  
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

# Configuration
commonConfiguration: |-
  maxmemory 512mb
  maxmemory-policy allkeys-lru
  save 900 1
  save 300 10
  save 60 10000

# Metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

# Security
networkPolicy:
  enabled: true
  allowExternal: false

podSecurityPolicy:
  enabled: true

