version: '3.8'

services:
  # Customer Portal Frontend
  customer-portal:
    build:
      context: ../../frontend/customer-portal
      dockerfile: Dockerfile
    container_name: freight-customer-portal
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - freight-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Dashboard Frontend
  admin-dashboard:
    build:
      context: ../../frontend/admin-dashboard
      dockerfile: Dockerfile
    container_name: freight-admin-dashboard
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - freight-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy for Frontend Routing
  frontend-proxy:
    image: nginx:alpine
    container_name: freight-frontend-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - freight-network
    depends_on:
      - customer-portal
      - admin-dashboard
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_logs:
    driver: local

networks:
  freight-network:
    external: true

